apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "karpenter-provisioners.labels" . | nindent 4 }}
spec:
  labels:
    beta.crowdstrike.com/pool: {{ .Release.Name }}
  {{- with .Values.requirements }}
  requirements:
    {{- with .capacityType }}
    - key: "karpenter.sh/capacity-type"
      operator: In
      values:
        {{- toYaml . | nindent 6 }}
    {{- end }}    
    {{- with .instanceType }}
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values:
      {{- toYaml . | nindent 6 }}
    {{- end }}    
  {{- end }}    
    
  limits:
    resources:
      cpu: {{ .Values.limits.resources.cpu }}
      cpu: {{ .Values.limits.resources.memory }}
  provider:
    subnetSelector:
      kubernetes.io/cluster/{{ .Values.clusterID }}: "shared"
    securityGroupSelector:
      kubernetes.io/cluster/{{ .Values.clusterID }}: "shared"
    tags:
      kubernetes.io/cluster/{{ .Values.clusterID }}: "shared"
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000 # = 30 days * 86400





