apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "karpenter-provisioners.labels" . | nindent 4 }}
spec:
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}    
  {{- with .Values.requirements }}
  requirements:
    {{- with .capacityType }}
    - key: "karpenter.sh/capacity-type"
      operator: In
      values:
        {{- toYaml . | nindent 6 }}
    {{- end }}    
    {{- with .instanceType }}
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values:
      {{- toYaml . | nindent 6 }}
    {{- end }}    
  {{- with .arch }}
    - key: "kubernetes.io/arch"
      operator: In
      values:
      {{- toYaml . | nindent 6 }}
    {{- end }}    
  {{- end }}        
  limits:
    resources:
      cpu: {{ .Values.limits.resources.cpu }}
      memory: {{ .Values.limits.resources.memory }}
  provider:
    subnetSelector:
      Name: "*public*"
    securityGroupSelector:
      karpenter.sh/discovery/{{ .Values.clusterID }}: {{ .Values.clusterID }}    
    tags:
      karpenter.sh/discovery/{{ .Values.clusterID }}: {{ .Values.clusterID }}    
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000 # = 30 days * 86400





